name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

 build_and_push:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu container

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out the repository
      - name: check username and password
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          echo ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Logs in to Docker Hub using secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ai_service:latest .

      - name: Tag and Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ai_service:latest  # Pushes to Docker Hub
